version: '3.7'

services:
  mongodb:
    image: mongo:4.2.8
    hostname: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    volumes:
      - .:/app/worker
      - /etc/localtime:/etc/localtime
    links:
      - mongodb
    depends_on:
      - mongodb
    env_file:
      - .env
#  app:
#    build: ./app
#    ports:
#      - "3001:3000"
#    depends_on:
#      - mongodb
#    environment:
#        - MONGODB_URI="mongodb://admin:admin@mongodb:27017/admin"
#
